---
- name: install apache
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: display ip
      debug:
            var: ansible_all_ipv4_addresses[0]
    - name: install apache on ubuntu
      when: ansible_distribution == "Ubuntu"
      package:
        name: apache2
        state: present
    - name: start  apache on ubuntu
      when: ansible_distribution == "Ubuntu"
      service:
        name: apache2
        state: started
    - name: copy index.html.j2 file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

